### ISSUE TITLE
opensubtitles download

### ISSUE THREAD

**Issue by Wally73** [phdelodder/SubTools#1]
Downloads van opensubtitels resulteert in een onbruikbare srt file 

Marco.Polo.2014.S01E05.Hashshashin.1080p.NF.WEBRip.DD5.1.x264-NTb.srt is

http://gyazo.com/f29b1ee440aaed3daf8e66199867bec2 (screenshot) 

MultiSubDownloader-v0.1.25 versie

**Comment by phdelodder** [comment]
Jbier is niet meer supporter maar multisub is voor iedereen nu beschikbaar
