### ISSUE TITLE
Feature request: Download exact match only

### ISSUE THREAD

**Issue by peter-vb** [phdelodder/SubTools#10]
What I like to have is the following when running the tool from the command line:
* Download only the subtitle if it is an exact match.

So I do not get this: 
 *Downloaded sub for episode: Grimm.S04E08.720p.HDTV.X264-DIMENSION.mkv using these subs: Grimm.S04E08.HDTV.x264-LOL.srt*

* When there are multiple subtitles available I would still like to download always the exact match

So it would download the 1st of the example below:

1. *Debug: getSubtitlesFiltered: found EXACT match: Sleepy.Hollow.S02E12.720p.HDTV.x264-IMMERSE.srt*
2. *Debug: getSubtitlesFiltered: found KEYWORD match: Sleepy.Hollow.S02E12.720p.HDTV.x264-IMMERSE.srt*
3. *Debug: getSubtitlesFiltered: found KEYWORD match: Sleepy.Hollow.S02E12.HDTV.x264-ASAP.srt*

I was not able to achieve this.
Is this already possible with the settings? Then I would love know which to set. As i have tried already a few of them.
If it is not yet possible it would be a great new feature.

**Comment by phdelodder** [comment]
Did you check the exacte check box in preference -> options. See screenshot if you can't find it. It's the only option checked under "zoek methode"

or enable in prefs: "<entry key="OptionSubtitleExactMatch" value="true"/>"

![selection_002](https://cloud.githubusercontent.com/assets/7259755/5696325/53f6cbc0-99cc-11e4-9a90-d37f76c1be3e.jpg)

Note: Only check exacte not keyword!

**Comment by peter-vb** [comment]
I tested it.
And it does exactly what I requested.
Thanks this request can be closed
