### ISSUE TITLE
Serieafleveringen wel geindexeerd, niet gedownload.deel 2 (phdelodder: Rework Download Selection)

### ISSUE THREAD

**Issue by Masterbreel** [phdelodder/SubTools#14]
Weer hetzelfde probleem sinds de update. Heb er 1 aflevering laten indexeren en proberen de subtitle te vinden. Ik heb de ondertitel ondertussen ook met de hand gedownload (niet dezelfde map) en dus vastgesteld dat de ondertitel bestaat. Hieronder linkje naar de pastebin met de TRACE erin.

http://pastebin.com/P48f6a9j

**Comment by phdelodder** [comment]
Inderdaad de ondertitel bestaat, zie het duidelijk in de trace. Maar de reden dat het niet werkt is om dat de ondertitel source addic7ed is, en in de aangegeven quality geen tekst voor komt die toepasselijk is voor jou download regel. 

Wat ik wel merk is dat in de auto download regels misschien wel een extra checkboxable feature zou kunnen toevoegen! Namelijk kijken op release team, die heb ik gezien is wel aanwezig in de subtitle als in de bestandsnaam.

**Comment by phdelodder** [comment]
Ik zal de volledige ondertitel selectie herzien en dit zou moeten resulteren in meer correcter approche. De eerste commits gaan deze richting van een complete refactor met meer controle voor de gebruiken in de opties.

**Comment by phdelodder** [comment]
Gelieve beta1 te testen om te kijken als dit issue is opgelost

**Comment by Masterbreel** [comment]
waar vind ik de beta1?

**Comment by phdelodder** [comment]
https://github.com/phdelodder/SubTools/releases/tag/1.0.0-beta1

**Comment by Masterbreel** [comment]
Helaas....

Date: Fri, 16 Jan 2015 03:15:11 -0800

**Comment by phdelodder** [comment]
In de opties heb ik nieuwe voorzien voor de automatische selectie

**Comment by RobinHoutevelts** [comment]
Het probleem zal wel opgelost zijn met te zoeken naar de vermelding van het team ( releasegroup had ik een betere naamgeving gevonden ).
Echter heb ik het willen repliceren en bij mij wordt er niet eens gekeken naar addic7ed.

Stopt het zoeken als er een match gevonden wordt?

Trace:
http://pastebin.com/raw.php?i=dFgAB3tt
Screenshot download opties: ( Addic7ed staat aangevinkt bij Serie Sources )
http://eih.bz/s1/1d4e59d39e.png

**Comment by phdelodder** [comment]
Je mag altijd de naamgeving wijzigen ;) . Ik gebruik de laatste release voor mijn dagelijkse versie en heb geen enkel probleem. 

Ik zal zo snel mogelijk een nieuwe release maken met extra logging om duidelijk te zien wat de settings zijn voor zoeken en selectie.

**Comment by RobinHoutevelts** [comment]
Perfect, ik heb ook een nieuw issue #15  aangemaakt om dit soort issues ( vind subtitles maar kan niet downloaden ) te voorkomen.

**Comment by phdelodder** [comment]
Dit is een versie met extra logging  https://www.dropbox.com/s/okcxrvs0c7i4qjq/multisubdownloader-1.0.0-SNAPSHOT.one-jar.jar?dl=0 gelieve deze te testen

**Comment by phdelodder** [comment]
@Masterbreel de nieuwe versie is uit : https://github.com/phdelodder/SubTools/releases/tag/subtools-1.0.0-BETA1

kan je die aub even testen?

**Comment by Masterbreel** [comment]
Had het gezien (ook via bierdopje) mara nog geen tijd gehad helaas.
 
Date: Thu, 5 Feb 2015 23:43:53 -0800

**Comment by Wally73** [comment]
hij zoekt ook op podnapisi maar die heb ik NIET geactiveerd in serie
sources (alleen addic7ed en opensubtitles) (in gui)

Als ik alleen addic7ed aan heb zoekt ie idd alleen op addic7ed maar zodra
ik opensubtitles dr ook bijzet gaat ie zelf ook zoeken op podnapisi

**Comment by phdelodder** [comment]
@Wally73 fix in volgende versie, bedankt om het te melden

**Comment by Wally73** [comment]
Mappen in map doorzoeken wordt niet onthouden

On Fri, Feb 6, 2015 at 12:03 PM, Philippe Delodder <notifications@github.com

**Comment by phdelodder** [comment]
@Wally73  in de volgende release is het in orde

**Comment by phdelodder** [comment]
@Masterbreel , @RobinHoutevelts , @Wally73  een nieuwe beta om te testen:
https://github.com/phdelodder/SubTools/releases/tag/subtools-1.0.0-BETA2

**Comment by Wally73** [comment]
zoek resultaten worden niet gereset na t selecteren van een andere map

mappen in map wordt nu wel onthouden ;) en alleen addic7ed en opensubtitles
selecteren werkt nu ook

On Mon, Feb 9, 2015 at 11:13 AM, Philippe Delodder <notifications@github.com

**Comment by phdelodder** [comment]
@Wally73 je mag voor het issue(zoek resultaten) een aparte issue aanmaken, dat maakt het wat overzichtelijker ;)

**Comment by RobinHoutevelts** [comment]
Ik denk dat alles dat hier vermeld is geweest ondertussen gefixed is?

**Comment by phdelodder** [comment]
Idd is gefixed
