### ISSUE TITLE
Filter found subtitles before showing #found subtitles

### ISSUE THREAD

**Issue by RobinHoutevelts** [phdelodder/SubTools#15]
When you have quality filters set, the found subtitles should be filtered before showing how many subtitles the search yielded.

It should be shown as < matched/total >.

This shouldn't happen ( although it has generated a few issues that got fixed )
![image](https://cloud.githubusercontent.com/assets/9056689/5781878/7c86287c-9db6-11e4-93a0-7ffff8b70273.png)

In this case it should be shown as 0/2 so the user knows that 2 subtitles exist, but can't be downloaded due to his set filters.

**Comment by phdelodder** [comment]
I can understand but the getAutomaticSubtitleSelection is executed when you press "Download geselecteerde" So need to update the selection based on the response of "Nothing Found" after you pressed or before you press?

**Comment by phdelodder** [comment]
See pull request #42
