### ISSUE TITLE
Subtitle rename to match mkv file?

### ISSUE THREAD

**Issue by peter-vb** [phdelodder/SubTools#20]
What I noticed lately is that some subtitles are downloaded ending with v1.
For example the subtitle Castle.2009.S07E11.720p.HDTV.X264-DIMENSION-v1.srt is downloaded for Castle.2009.S07E11.720p.HDTV.X264-DIMENSION.mkv.
As a result they are not working without me renaming them manually.
I have the option for exact match only <entry key="OptionSubtitleExactMatch" value="true"/>

Is there an option which will rename the subtitle to exact match the mkv filename?

**Comment by phdelodder** [comment]
The reason you have v1 is because to option "-downloadall" is enabled when starting the program.

**Comment by peter-vb** [comment]
Thanks. 
I do run it with the option -downloadall.
I will remove that option.

I see now the description of -downloadall. "Download all found subs using '-v1' system"
What does it mean or how does it work "-v1 system"?

**Comment by phdelodder** [comment]
All the subs are downloaded and on every sub -vX is added

So 2 available sub = -v1 and -v2 

Hopefully it's clear

**Comment by peter-vb** [comment]
Sorry for the late response was out if the country.
Thanks it is clear.
