### ISSUE TITLE
File index progresss not visible 

### ISSUE THREAD

**Issue by phdelodder** [phdelodder/SubTools#48]
For java 1.8 this commit offers a workaround: https://github.com/phdelodder/SubTools/commit/dd722e0013fad7d753fe3ec852713737994ea7bf

But for 1.7 I dont have a clue on how to solve it. 

https://www.dropbox.com/s/fwo4ld9lngq21ox/error-2015-02-09_08.30.00%20%281%29-001.mkv?dl=0

**Comment by RobinHoutevelts** [comment]
Can be closed. Fixed in #52
