### ISSUE TITLE
Error "character to be escaped is missing" when downloading

### ISSUE THREAD

**Issue by peter-vb** [phdelodder/SubTools#5]
When selecting a subtitle to download I get a pop-up with an error.

== Trace ==
Trace: class org.lodder.subtools.multisubdownloader.MainWindow: (download) 

Trace: class org.lodder.subtools.multisubdownloader.gui.workers.DownloadWorker: (doInBackground) Rows to thread: 1

Debug: determineWhatSubtitleDownload: # found subs: 2

Debug: determineWhatSubtitleDownload: Multiple subs detected

Debug: determineWhatSubtitleDownload: Select subtitle with dialog

Debug: Downloaded subs for episode: sons.of.anarchy.s06e03.720p.hdtv.x264-2hd.mkv using these subs: Sons.of.Anarchy.S06E03.HDTV.x264-2HD.srt

Trace: Actions: (download) LibraryActionVerplaatsen

Trace: TheTVDBApi: (createApiUrl) 

Trace: TheTVDBApi: (createApiUrl) create part: /series/82696

Trace: XmlHTTPAPI: (getXMLDisk) timeout: 2592000

Debug: Found Disk cached element: http://thetvdb.com/api/A1720D2DDFDCE82D/series/82696

Trace: TheTVDBSerie: (parseSerieNode) Element: <?xml version="1.0" encoding="UTF-8"?><Series>    <id>82696</id>    <Actors>|Charlie Hunnam|Katey Sagal|Ron Perlman|Mark Boone Junior|Ryan Hurst|Theo Rossi|Tommy Flanagan|Kim Coates|Maggie Siff|Niko Nicotera|Drea de Matteo|Jimmy Smits|William Lucking|David Labrava|Dayton Callie|Johnny Lewis|Taylor Sheridan|Donal Logue|Ally Walker|Ray McKinnon|Luis Torres|Danny Trejo|Christopher Douglas Reed|Timothy V. Murphy|Kenneth Choi|Rockmond Dunbar|Emilio Rivera|Kurt Sutter|Winter Ave Zoli|Michael Ornstein|Titus Welliver|Adam Arkin|</Actors>    <Airs_DayOfWeek>Tuesday</Airs_DayOfWeek>    <Airs_Time>10:00 PM</Airs_Time>    <ContentRating>TV-MA</ContentRating>    <FirstAired>2008-09-03</FirstAired>    <Genre>|Crime|Drama|Thriller|</Genre>    <IMDB_ID>tt1124373</IMDB_ID>    <Language>en</Language>    <Network>FX</Network>    <NetworkID/>    <Overview>Sons of Anarchy is an adrenalized drama with darkly comedic undertones that explores a notorious outlaw motorcycle clubâ€™s (MC) desire to protect its livelihood while ensuring that their simple, sheltered town of Charming, California remains exactly that, charming. The MC must confront threats from drug dealers, corporate developers, and overzealous law officers. Behind the MCâ€™s familial lifestyle and legally thriving automotive shop is a ruthless and illegal arms business driven by the seduction of money, power, and blood.</Overview>    <Rating>8.9</Rating>    <RatingCount>259</RatingCount>    <Runtime>60</Runtime>    <SeriesID>75303</SeriesID>    <SeriesName>Sons of Anarchy</SeriesName>    <Status>Ended</Status>    <added/>    <addedBy/>    <banner>graphical/82696-g.jpg</banner>    <fanart>fanart/original/82696-3.jpg</fanart>    <lastupdated>1420669333</lastupdated>    <poster>posters/82696-1.jpg</poster>    <tms_wanted_old>1</tms_wanted_old>    <zap2it_id>EP01074337</zap2it_id>  </Series>

Trace: XMLHelper: (getStringTagValue) sTag:id

Trace: XMLHelper: (getStringTagRawValue) sTag:id

Trace: XMLHelper: (getStringTagValue) sTag:Actors

Trace: XMLHelper: (getStringTagRawValue) sTag:Actors

Trace: XMLHelper: (getStringTagValue) sTag:Airs_DayOfWeek

Trace: XMLHelper: (getStringTagRawValue) sTag:Airs_DayOfWeek

Trace: XMLHelper: (getStringTagValue) sTag:Airs_Time

Trace: XMLHelper: (getStringTagRawValue) sTag:Airs_Time

Trace: XMLHelper: (getStringTagValue) sTag:ContentRating

Trace: XMLHelper: (getStringTagRawValue) sTag:ContentRating

Trace: XMLHelper: (getStringTagValue) sTag:FirstAired

Trace: XMLHelper: (getStringTagRawValue) sTag:FirstAired

Trace: XMLHelper: (getStringTagValue) sTag:Genre

Trace: XMLHelper: (getStringTagRawValue) sTag:Genre

Trace: XMLHelper: (getStringTagValue) sTag:IMDB_ID

Trace: XMLHelper: (getStringTagRawValue) sTag:IMDB_ID

Trace: XMLHelper: (getStringTagValue) sTag:Language

Trace: XMLHelper: (getStringTagRawValue) sTag:Language

Trace: XMLHelper: (getStringTagValue) sTag:Network

Trace: XMLHelper: (getStringTagRawValue) sTag:Network

Trace: XMLHelper: (getStringTagValue) sTag:Overview

Trace: XMLHelper: (getStringTagRawValue) sTag:Overview

Trace: XMLHelper: (getStringTagValue) sTag:Rating

Trace: XMLHelper: (getStringTagRawValue) sTag:Rating

Trace: XMLHelper: (getStringTagValue) sTag:Runtime

Trace: XMLHelper: (getStringTagRawValue) sTag:Runtime

Trace: XMLHelper: (getStringTagValue) sTag:SeriesID

Trace: XMLHelper: (getStringTagRawValue) sTag:SeriesID

Trace: XMLHelper: (getStringTagValue) sTag:SeriesName

Trace: XMLHelper: (getStringTagRawValue) sTag:SeriesName

Trace: XMLHelper: (getStringTagValue) sTag:Status

Trace: XMLHelper: (getStringTagRawValue) sTag:Status

Trace: XMLHelper: (getStringTagValue) sTag:lastupdated

Trace: XMLHelper: (getStringTagRawValue) sTag:lastupdated

Trace: XMLHelper: (getStringTagValue) sTag:zap2it_id

Trace: XMLHelper: (getStringTagRawValue) sTag:zap2it_id

-------
java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.regex.Matcher.appendReplacement(Unknown Source)
	at java.util.regex.Matcher.replaceAll(Unknown Source)
	at java.lang.String.replaceAll(Unknown Source)
	at org.lodder.subtools.multisubdownloader.lib.library.PathLibraryBuilder.episodeBuildPath(PathLibraryBuilder.java:58)
	at org.lodder.subtools.multisubdownloader.lib.library.PathLibraryBuilder.buildPath(PathLibraryBuilder.java:24)
	at org.lodder.subtools.multisubdownloader.lib.Actions.download(Actions.java:231)
	at org.lodder.subtools.multisubdownloader.lib.Actions.download(Actions.java:545)
	at org.lodder.subtools.multisubdownloader.lib.Actions.download(Actions.java:552)
	at org.lodder.subtools.multisubdownloader.gui.workers.DownloadWorker.doInBackground(DownloadWorker.java:57)
	at org.lodder.subtools.multisubdownloader.gui.workers.DownloadWorker.doInBackground(DownloadWorker.java:21)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
-------

**Comment by phdelodder** [comment]
Is it possible to attach or pastbin your prefs + full trace?

**Comment by peter-vb** [comment]
prefs
http://pastebin.com/WjQgHQLi

Trace file
http://pastebin.com/CPdKgXi7

**Comment by RobinHoutevelts** [comment]
Sorry for the Pull-request confusion.. Forgot the checkout the dev-branch instead of master.

**Comment by phdelodder** [comment]
Can you please test if it's fixed in this version? https://www.dropbox.com/s/vej0eczege4b628/multisubdownloader-0.1.28.one-jar.jar?dl=0

**Comment by peter-vb** [comment]
I just tested it. It still gives the same error.
Trace file can be found here.
pastebin.com/CGVtAse6

**Comment by RobinHoutevelts** [comment]
I'm not sure the link he gave you contained my pull-request as it seems to be the same link posted in #4.

**Comment by peter-vb** [comment]
If you provide me with another link I can test it right now

**Comment by RobinHoutevelts** [comment]
https://www.dropbox.com/s/mj2xh1um0wp4sm0/multisubdownloader.jar?dl=0

**Comment by peter-vb** [comment]
Thanks Robin. 
It works with the version you just provided.

**Comment by RobinHoutevelts** [comment]
Np, keep reporting bugs and feature requests. I'm sure it's appreciated ;-)
