### ISSUE TITLE
search results aren't reset after selecting another scanfolder

### ISSUE THREAD

**Issue by Wally73** [phdelodder/SubTools#50]
main folder view : http://gyazo.com/acb933589704093b204705ae941ec284

when switching to another folder the results are put under the results from the main folder 
http://gyazo.com/0e7cb04a80dc6868faea4352643e2c7f instead of clearing the result list and only show the ones of that folder

**Comment by RobinHoutevelts** [comment]
Duplicate of https://github.com/phdelodder/SubTools/issues/47 which is fixed.
This can be closed.
