### ISSUE TITLE
Null pointer exception when running on Linux

### ISSUE THREAD

**Issue by peter-vb** [phdelodder/SubTools#6]
When running multisub on my NAS (Linux) I get a nullpointer exception (see trace below).
Not sure if it is caused by the prefs file (on the bottom of this issue) or usage of wrong parameters.

I use the following 2 commands to run it.
/usr/local/jre/bin/java -jar "/share/Downloads/MultiSubDownloader-v0.1.27.jar" --nogui --importpreferences "/share/Downloads/multi_prefs.xml" --language nl

/usr/local/jre/bin/java -jar "/share/Downloads/MultiSubDownloader-v0.1.27.jar" --nogui --folder "/share/Downloads/sabnzbd/tv/Sons of Anarchy S06E03 720p HDTV x264-2HD" --debug --recursive --language nl --trace

=== Trace ===
Auto updating mapping ....
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Trace: XMLHelper: (getIntTagValue) sTag:tvdbid
Trace: XMLHelper: (getStringTagValue) sTag:scene
Trace: XMLHelper: (getStringTagRawValue) sTag:scene
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at org.lodder.subtools.multisubdownloader.App.main(App.java:76)
        ... 6 more

==END Trace ===

I added captures of the prefs file used as I cannot attach or paste it into this issue report

![capture](https://cloud.githubusercontent.com/assets/10454402/5669692/18660f84-977a-11e4-8e8a-da4ed429e1e6.PNG)

![capture2](https://cloud.githubusercontent.com/assets/10454402/5669713/57dcdf3a-977a-11e4-8484-55e5a52dc926.PNG)

**Comment by phdelodder** [comment]
Can you test with this version? https://www.dropbox.com/s/vej0eczege4b628/multisubdownloader-0.1.28.one-jar.jar?dl=0

**Comment by peter-vb** [comment]
Deze versie werkt voor mij.
Ik krijg geen foutmelding meer.
