### ISSUE TITLE
Bugs 1.0.0-BETA4

### ISSUE THREAD

**Issue by ThaTim** [phdelodder/SubTools#62]
- Scrore instead of score in download screen
- Program kept hanging till 3 times at series 12 monkeys
- Logging errors:
http://pastebin.com/mFFrMcX6

You can see the following in the log:
A couple of times 404 errors. First 2 from the show Arrow
The 5th from The Blacklist
The 6th from The Mentalist

When I downloaded the Subtitle for House of Lies it appeared 2 times in my log

**Comment by phdelodder** [comment]
Is it possible tot add the releases for each show you mentioned is easier to test and see what issue it is

**Comment by phdelodder** [comment]
A full trace log would also be nice!

**Comment by phdelodder** [comment]
I have tried every possibilty and I'm not able to reproduce it. 

Can you delete the cache .MultiSubDownloader for in you home dir and try again?

**Comment by ThaTim** [comment]
The shows I meant earlier were:
Arrow.S03E13.Canaries.720p.HDTV.x264-DIMENSION
The.Blacklist.S02E11.Ruslan.Denisov.720p.HDTV.x264-DIMENSION
The.Mentalist.S07E12-E13.Brown.Shag.Carpet.-.White.Orchids.720p.HDTV.x264-DIMENSION

After clearing my cache I didn't encounter any of the previous errors.
This is my complete log after deleting my cache:
Controleren voor nieuwe update
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
Error: Error response: 404 For url: http://www.addic7ed.com/serie/south_park/18/9/#rehash
Error: Error response: 404 For url: http://www.addic7ed.com/serie/south_park/18/10/#happyholograms
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
----- Download Options ------
 - OptionsAlwaysConfirm : true
-----------------------------

**Comment by phdelodder** [comment]
Thanks, I have pushed a fix so that # sign error is fixed for south park. Will be in next release
