### ISSUE TITLE
Standaard voorkeuren aangeven

### ISSUE THREAD

**Issue by Masterbreel** [phdelodder/SubTools#66]
In de nieuwe update, maar 'scores' is het niet meer mogelijk om standaard voorkeuren in te geven.

Ik heb bijvoorbeeld bijna altijd 720p.HDTV en uit ervaring weet ik dat het met die van addicted bijv vrij vaak goed gaat. Ik zou dus graag willen kunnen aangeven dat ik die standaard voorkeuren heb. Zeker als ik 15 afleveringen tegelijk van ondertitels wil voorzien is het een klus om elke keer een vinkje te moeten geven, zo kan het indexeren dus niet meer als ik weg loop van de PC (en met die addicted 15 sec regel kan het wel even duren tegenwoordig)

**Comment by phdelodder** [comment]
@Masterbreel standaard voorkeuren kan ik eventueel een selectie lijst samenstellen waar je 1 waarde kan kiezen die je als default instelt. Als je de default in de lijst met beschikbare ondertitels is gevonden zal het ook gedownload worden en de counter wordt ook aangepast aan de standaard waarde. 

Door de counter aan te passen zal je enkel 1 of 0 hebben, je gaat geen andere mogelijkheid meer hebben of wil je nog wil de optie hebben om even af te wijken van de standaard voorkeur?

**Comment by Masterbreel** [comment]
Áls het mogelijk is, zou ik inderdaad zeggen dat als de voorkeurondertitel beschikbaar is (bijv: HDTV, od BRRIP), dan die downloaden. Als die niet beschikbaar is, dan de normale route. Dus handmatig kiezen waarbij de tool een score geeft.

Nu ben ik wel benieuwd naar hoe de score tot stand komt, maar dat ter zijde.

Date: Tue, 3 Mar 2015 00:13:52 -0800

**Comment by phdelodder** [comment]
@Masterbreel kan je testen: https://www.dropbox.com/s/go6x9ex3zw7s03t/multisubdownloader-1.1.0-SNAPSHOT-jar-with-dependencies.jar?dl=0

**Comment by phdelodder** [comment]
@Masterbreel Gelieve aan te geven als je hebt kunnen testen?

**Comment by Masterbreel** [comment]
Hallo Lodder,
 
Ik heb het kunnen testen en het werkt volgens mij prima! Alleen pikte ik wel iets geks op laatst. Ik had house of cards verkregen, de ondertitels die hierbij hoorde (naam exacte match) stonden wel op addicted, maar werden door de app niet opgepikt. Ik had de webrip versie, terwijl de app deze versie niet kon vinden (en slechts 1 match aangaf, terwijl er wel 5 of 6 verschillende versies waren). Ik had geen voorkeuren aangegeven.
 
Gr
Master
 
Date: Mon, 9 Mar 2015 02:55:05 -0700

**Comment by phdelodder** [comment]
Als je dit hebt mag je een altijd een trace log aan een nieuwe ticket koppelen

**Comment by Masterbreel** [comment]
zal ik de volgende keer doen!
 
Date: Mon, 9 Mar 2015 03:08:58 -0700
