### ISSUE TITLE
Overzicht van verkregen subtitles.

### ISSUE THREAD

**Issue by Sailsoft2015** [phdelodder/SubTools#72]
Aangezien niet alle verkregen srt's de kwaliteit uit de Bierdopje tijd hebben, controleer ik ze na downloaden altijd even op synchroon lopen en glbale kwaliteit.  Hiervoor noteer ik dus van de aangevinkte subs de serienaam + episode.

Is het mogelijk om van alle aangevinkte (en dus gedownloade) srt's na afloop een overzicht te krijgen op het scherm, dan wel in een logfile ?

Toevoeging: Zie net dat die info tegenwoordig al onderin het log venster staat.  Blijft de vraag over of deze info automatisch in een logfile geschreven kan worden.

**Comment by phdelodder** [comment]
Die info wordt niet in een log file geschreven. Momenteel wordt gebruik gemaakt van een custom logging die ik zelf heb geschreven. In een volgende versie is het de bedoeling om een logging framework te gaan gebruiken die het mogelijk maakt om naar verschillende output mogelijk te maken. 

Maar omwille dat het op zo veel locaties wordt gebruikt is het een groot werk om het aan te passen.

**Comment by Wally73** [comment]
je kan de backup download functie gebruiken naar een folder naar keuze en
dat gebruiken (soort van) als log

2015-03-09 7:56 GMT+01:00 Philippe Delodder <notifications@github.com>:
