### ISSUE TITLE
Downloaded subs not showing

### ISSUE THREAD

**Issue by ThaTim** [phdelodder/SubTools#73]
All the downloaded subs are nowhere to be found on my computer. I've tried several times.
What I do: I select the sub I want, and I click on OK. Normally the subs are downloaded in my standard search map.

Also an enhancement: The download screen where you can select which sub to download is clear then the download screen in previous versions. This can be solved by making the download screen bigger instead of the fixed size now. This is just my opinion

**Comment by phdelodder** [comment]
this is the latest snapshot version can you try it?

https://www.dropbox.com/s/eot8pblndi2f6iz/multisubdownloader-1.2.0-SNAPSHOT-jar-with-dependencies.jar?dl=0

I'll will look into th screen size to make it bigger

**Comment by ThaTim** [comment]
I've tried with this newest version and the downloaded files are still nowhere to be found.
Also there is no mention in the log that the files downloaded.

**Comment by phdelodder** [comment]
https://www.dropbox.com/s/eot8pblndi2f6iz/multisubdownloader-1.2.0-SNAPSHOT-jar-with-dependencies.jar?dl=0

New update which fixes the issue! 

Can you also give a screenshot of the screen with your remarks

**Comment by ThaTim** [comment]
The new update fixes the download issue. Thanks

As you can see in the attached image, the text between the black lines is not fully visible. It is only fully visible after I extend the top line. But that's not easy to do when I have to download 20 or more subs. With a bigger size of that particular screen, my problem is solved.
Thanks in advance and keep up the good work. 

![screenshot multisub 18-03-2015](https://cloud.githubusercontent.com/assets/11080175/6717580/c7bf317c-cdad-11e4-97bd-ade7e35e557f.jpg)

**Comment by ThaTim** [comment]
The new update fixes the download issue. Thanks.

As you can see in the screenshot the text between the 2 black lines is not fully visible. I selected the right file always by looking at the file name. I can shift the border so that the text will be fully visible, but that's not easy to do with 20 or more subs to be downloaded, and those settings can't be saved. With a full screen I don't have to make the file name visible, because that's automated with the fullscreen, I hope.
![screenshot multisub 18-03-2015](https://cloud.githubusercontent.com/assets/11080175/6717787/3f8bde7a-cdaf-11e4-94c1-ab36b1355e0d.jpg)

**Comment by phdelodder** [comment]
When you leave your cursor over the field the full text appears. I'll try to make it bigger.

**Comment by phdelodder** [comment]
Latest version: https://www.dropbox.com/s/eot8pblndi2f6iz/multisubdownloader-1.2.0-SNAPSHOT-jar-with-dependencies.jar?dl=0

**Comment by ThaTim** [comment]
New version works like a charm, at the first try.
Thanks for the adjustment in the download screen
