### ISSUE TITLE
files not recognized

### ISSUE THREAD

**Issue by ThaTim** [phdelodder/SubTools#76]
Hello,

I've got some files with the .m4v extension and Multisub v1.2.0 does not recognize them as video files and doesn't search for subs for those files.
When I set logging to ALL, I only see this:
[TRACE] SearchAction is being executed
[TRACE] getFileListing: dir [E:\uTorrent\Fringe Season 1] Recursive [false] languageCode [nl] forceSubtitleOverwrite [false]

**Comment by Wally73** [comment]
you're a version behind

https://github.com/phdelodder/SubTools/releases/tag/subtools-1.2.1

try that one to see if it works (i never use m4v files so i can't tell if
it works or not)

**Comment by ThaTim** [comment]
Thanks for the new version.

I've cleared my cache en tried the new version.
It still won't recognize my m4v files and the logging is the same as in my first message

**Comment by phdelodder** [comment]
The m4v extension needs to be added.

**Comment by Wally73** [comment]
never seen subs for m4v version but maybe the mp4 sub works on them

On Wed, Apr 15, 2015 at 3:47 PM, Philippe Delodder <notifications@github.com
