### ISSUE TITLE
Problem with Podnapisi

### ISSUE THREAD

**Issue by TheFonZzz** [phdelodder/SubTools#82]
Bij elke run krijg ik de melding

[ERROR] API PODNAPISI getXML

Ik zag dat er 2 maanden geleden al een aanpassing is gedaan, maar kan geen nieuwe versie downloaden. Heb je inmiddels al een oplossing hiervoor gevonden?

**Comment by phdelodder** [comment]
Er is een nieuwe release: https://github.com/phdelodder/SubTools/releases/tag/subtools-1.2.5
