### ISSUE TITLE
thetvdb api v1 eol 

### ISSUE THREAD

**Issue by Wally73** [phdelodder/SubTools#84]
please change to api v2 version of the tvdb api 
v1 will be  discontinue the old API as of October 1st, 2017

Documentation for v2 API is found at https://api.thetvdb.com/swagger

**Comment by EotT123** [comment]
lodder, I updated the code to use theTVDB api v2: https://github.com/EotT123/SubTools/commit/a93430c5a2f179a8ea3adb04e9d89546dca505e8#diff-21ae59336c250be2e28c4734d689c46a. It's not perfect, but I tried to keep the changes as minimal as possible, without impacting/changing other classes.

**Comment by phdelodder** [comment]
@EotT123 thanks for the changes, but I have noticed also a change in the pom.xml. 

I will adapt the code to your suggestion but keep in mind that I will create a api V2 class instead, easier I think to start fresh.

**Comment by phdelodder** [comment]
@EotT123:  https://github.com/phdelodder/SubTools/commit/499ec6107fe703605be451d0bc68228fdcae9f88

**Comment by Denniswolt** [comment]
Thanks for your effort. But how do I download this?

I'am using windows and I only see the 1.2.4 as the latest available version.

Do I need to create a executable myself or something?

**Comment by phdelodder** [comment]
The new version with v2 is not available, I'll need to test it first

**Comment by EotT123** [comment]
I know there could be better ways to do it. I just wanted to change as little as possible. Anyway, thanks for using the code. It was my first day on github, so I hope I did it right. 
I didn't test it thoroughly, just tried it a few times and it seems to be working. But more testing is advised (I didn't create any unit tests).

**Comment by phdelodder** [comment]
Fixed
