### ISSUE TITLE
Stuck after indexing

### ISSUE THREAD

**Issue by Denniswolt** [phdelodder/SubTools#85]
Hallo Lodder (en anderen),

weet iemand wat er mis is, na het indexeren wordt er niet gezocht naar ondertitels op de verschillende sites.

Alle hulp wordt zeer gewaardeerd.

**Comment by Belin1963** [comment]
hier hetzelfde probleem :-(

**Comment by sublover** [comment]
Hier hetzelfde probleem.
Ligt het soms aan de api? Volgens het issue "thetvdb api v1 eol " hieronder zou er naar versie 2 moeten worden geupdate

**Comment by JDDoe** [comment]
Hier ook hetzelfde probleem. Misschien heeft het te maken met de update van Windows bij mij per 21/10/2017.  Daarna kreeg ik dezelfde problemen.  Indexing als status, daarna blijft het proces hangen.

Hopelijk kan Lodder het probleem fixen.

**Comment by EotT123** [comment]
Er is een probleem bij het inlezen van deze lijst van uitzonderingen : http://midgetspy.github.io/sb_tvdb_scene_exceptions/exceptions.txt. (in constructor van class JTheTVDBAdapter).
Ik heb snel een nieuwe versie gemaakt, waar deze lijst niet meer ingelezen wordt (maar deze uitzonderingen zullen dus niet meer correct kunnen worden verwerkt). Je kan deze versie gebruiken, tot er een officiële nieuwe versie is: [multisubdownloader-1.2.6-SNAPSHOT-jar-with-dependencies.jar.zip](https://github.com/phdelodder/SubTools/files/1404344/multisubdownloader-1.2.6-SNAPSHOT-jar-with-dependencies.jar.zip)

**Comment by Belin1963** [comment]
OOOOOh je bent en engel !!!!!!! thanks het werkt !! :-)

**Comment by phdelodder** [comment]
Ik ben aan het kijken naar een oplossing

**Comment by Denniswolt** [comment]
Top Lodder, maar versie 1.2.4 lijkt nog de laatste versie te zijn en geeft niet aan dat er een update is.
Hoe komen wij nu aan versie 1.2.7 of 1.2.8?

**Comment by Wally73** [comment]
@Denniswolt https://github.com/phdelodder/SubTools/releases/download/subtools-1.2.7/multisubdownloader-1.2.7-jar-with-dependencies.jar
